### ISSUE TITLE
Version flag emits idempotent output

### ISSUE THREAD

**Issue by orhun** [ratatui-org/crates-tui#23]
For `crates-tui -V` I get the following output:

```bash
crates-tui 0.1.5-VERGEN_IDEMPOTENT_OUTPUT (2024-02-10)
```

This is probably due to missing commits (`.git` folder) during build process.

Any idea how to make the output better? I'm interested in submitting a PR.

**Comment by joshka** [comment]
Check the build.rs, and update it as necessary.

**Comment by kdheepak** [comment]
Hmm. Maybe we should not set the git describe content if it is not a hash? The content is generated by vergen but is used in cli.rs.
